AllCops:
  TargetRubyVersion: 2.4
  NewCops: disable
  SuggestExtensions: false
  Exclude:
   - vendor/bundle/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Documentation:
  Enabled: false
